# Generated by Django 4.1.5 on 2023-07-28 19:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeneratedBlog",
            fields=[
                (
                    "bookmark_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("blog_html_text", models.TextField(null=True)),
                ("intro_text", models.TextField(blank=True, null=True)),
                ("extra_context", models.TextField(blank=True, null=True)),
                (
                    "username",
                    models.CharField(default="to be generated", max_length=100),
                ),
                ("author", models.CharField(default="To be generated", max_length=255)),
                ("title", models.CharField(default="To be generated", max_length=255)),
                ("slug", models.SlugField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="pages/static/blog"
                    ),
                ),
                ("pub_date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "generated_blogs",
            },
        ),
        migrations.CreateModel(
            name="milk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="NewsChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("channel_id", models.CharField(blank=True, max_length=255, null=True)),
                ("slug", models.SlugField(max_length=255, null=True, unique=True)),
                ("tagline", models.CharField(blank=True, max_length=255, null=True)),
                ("politcial_spectrum", models.IntegerField(blank=True, null=True)),
                ("youtube_rank", models.IntegerField(blank=True, null=True)),
                ("fake_news_index", models.IntegerField(blank=True, null=True)),
                ("credibility_index", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField()),
                ("founded_year", models.IntegerField(blank=True, null=True)),
                (
                    "channel_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "headquarters",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("owner", models.CharField(blank=True, max_length=255, null=True)),
                ("language", models.CharField(blank=True, max_length=255, null=True)),
                ("official_website", models.URLField(blank=True, null=True)),
                ("youtube_channel", models.URLField(blank=True, null=True)),
                (
                    "twitter_handle",
                    models.URLField(blank=True, max_length=255, null=True),
                ),
                ("facebook_page", models.URLField(blank=True, null=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="static/news_logos"
                    ),
                ),
                (
                    "subscribers",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "facebook_likes",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "twitter_followers",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="petroluem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="sarso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="TopPopularPersons",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("person1_name", models.CharField(max_length=255)),
                ("person1_video_count", models.PositiveIntegerField(null=True)),
                ("person2_name", models.CharField(max_length=255)),
                ("person2_video_count", models.PositiveIntegerField(null=True)),
                ("person3_name", models.CharField(max_length=255)),
                ("person3_video_count", models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TrendingTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=200)),
                ("rank", models.IntegerField(unique=True)),
                ("synopsis", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["rank"],
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("transcript", models.TextField()),
                ("published_date", models.DateTimeField()),
                ("video_url", models.URLField(max_length=2000)),
                ("thumbnail_url", models.URLField(max_length=2000)),
                ("topic", models.CharField(max_length=255)),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="pages.newschannel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LiveNewsBulletin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(max_length=5000)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("first_video_timestamp", models.DateTimeField(null=True)),
                ("author", models.CharField(default="To be generated", max_length=255)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_bullets",
                        to="pages.topic",
                    ),
                ),
            ],
        ),
    ]
